apiVersion: apps/v1                
kind: Deployment                   
metadata:                          
  name: register-service                      
spec:                              
  selector:                        
    matchLabels:                   
      app: register-service                   
  template:                        
    metadata:                      
      labels:                      
        app: register-service                 
    spec:                          
      containers:                  
        - name: register-service              
          image: us-central1-docker.pkg.dev/psyched-freedom-427313-r9/register-service/register-service             
          resources:               
            limits:                
              memory: "128Mi"      
              cpu: "500m"          
          ports:                   
            - containerPort: 8082  
