apiVersion: v1        
kind: Service         
metadata:             
  name: register-service         
spec:                 
  selector:           
    app: register-service        
  ports:              
    - port: 8082      
      targetPort: 8082
